/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import entity.Bill;
import entity.BillDetail;
import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.Border;
import model.BillModel;
import tablemodel.TableModelBill;
import tablemodel.TableModelOrder;
import vendor.DigitDocument;

/**
 *
 * @author Admin
 */
public final class FrmBill extends javax.swing.JFrame {
    BillModel billModel = new BillModel();  // khởi tạo đối tượng model để lấy dữ liệu
    ArrayList<Bill> listBill = new ArrayList<>(); // danh sách hóa đơn
    ArrayList<BillDetail> listOrder = new ArrayList<>();  //danh sách order(truyện đã bán) của từng hóa đơn
    NumberFormat numf = NumberFormat.getInstance(); // định dạng số
    int dongchon; // dòng mà ng dùng chọn trong table
    /**
     * Creates new form FrmBill
     */
    
    // load giao diện cho bảng order
    public void LoadTableOrder()
    {
        tb_Order.setModel(new TableModelOrder(listOrder));
    }
    // load dữ liệu lên bảng
    public void LoadListOrderById(int id) throws ClassNotFoundException, SQLException
    {
        listOrder = billModel.getListOrderById(id);
        LoadTableOrder();
    }
    // load giao diện cho bảng hóa đơn
    public void LoadTableBill()
    {
        tb_Bill.setModel(new TableModelBill(listBill));
        tb_Bill.getColumnModel().getColumn(0).setPreferredWidth((int) (tb_Bill.getWidth()*0.07));
        tb_Bill.getColumnModel().getColumn(1).setPreferredWidth((int) (tb_Bill.getWidth()*0.1));
        tb_Bill.getColumnModel().getColumn(2).setPreferredWidth((int) (tb_Bill.getWidth()*0.2));
        tb_Bill.getColumnModel().getColumn(3).setPreferredWidth((int) (tb_Bill.getWidth()*0.2));
        tb_Bill.getColumnModel().getColumn(4).setPreferredWidth((int) (tb_Bill.getWidth()*0.175));
    }
    // load dữ liệu cho bảng hóa đơn
    public void LoadListBill() throws ClassNotFoundException, SQLException
    {
        listBill = billModel.getListBill();
        LoadTableBill();
    }
    
    public FrmBill() throws ClassNotFoundException, SQLException {
        initComponents();
        setLocationRelativeTo(null);
        lb_CodeBill.setText("null");
        LoadListBill();
        LoadTableOrder();
        
        tb_Bill.getTableHeader().setOpaque(false);
        tb_Bill.getTableHeader().setBackground(new Color(0,0,0,0));
        tb_Bill.getTableHeader().setForeground(new Color(0,153,153));
        tb_Bill.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,14));
        
        Border border = BorderFactory.createLineBorder(new Color(0,153,153));
        tb_Bill.getTableHeader().setBorder(border);
        
        txt_Search.setDocument(new DigitDocument());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_Exit = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Bill = new javax.swing.JTable();
        btn_DeleteBill = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        txt_Search = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lb_CodeBill = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lb_NameEmployee = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lb_NameCustomer = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lb_DateOrder = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lb_TotalMoney = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lb_Promotion = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lb_PayMoney = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_Order = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        date_From = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        date_To = new com.toedter.calendar.JDateChooser();
        btn_Fillter = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1119, 782));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_money_bag_filled_100px.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Quản Lí Hóa Đơn");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        btn_Exit.setBackground(new java.awt.Color(0, 153, 153));
        btn_Exit.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn_Exit.setForeground(new java.awt.Color(204, 0, 0));
        btn_Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Exit.setText("x");
        btn_Exit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Exit.setOpaque(true);
        btn_Exit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_ExitMouseMoved(evt);
            }
        });
        btn_Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ExitMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ExitMouseExited(evt);
            }
        });
        jPanel1.add(btn_Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 0, 50, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);

        tb_Bill.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tb_Bill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "1", "Trần Viết Trưởng", "Nguyễn Duy Tùng", "09/03/2019", "50000", "10000", "hihih"},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã Hóa Đơn", "Nhân Viên", "Khách Hàng", "Ngày ", "Thành Tiền", "Khuyến Mãi", "Ghi Chú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_Bill.setFocusable(false);
        tb_Bill.setRowHeight(30);
        tb_Bill.setSelectionBackground(new java.awt.Color(0, 153, 153));
        tb_Bill.setShowVerticalLines(false);
        tb_Bill.getTableHeader().setReorderingAllowed(false);
        tb_Bill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tb_BillMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tb_Bill);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 700, 460));

        btn_DeleteBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_delete_forever_filled_30px.png"))); // NOI18N
        btn_DeleteBill.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_DeleteBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_DeleteBillMouseClicked(evt);
            }
        });
        jPanel2.add(btn_DeleteBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 40, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 210, 10));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_search_24px.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        txt_Search.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_Search.setText("Nhập mã hóa đơn");
        txt_Search.setBorder(null);
        txt_Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_SearchMouseClicked(evt);
            }
        });
        txt_Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_SearchKeyReleased(evt);
            }
        });
        jPanel2.add(txt_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 170, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Mã Hóa Đơn : ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 60, -1, -1));

        lb_CodeBill.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_CodeBill.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lb_CodeBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 60, 60, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Nhân Viên     : ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 90, 100, -1));

        lb_NameEmployee.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_NameEmployee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_NameEmployee.setText("null");
        jPanel2.add(lb_NameEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 90, 140, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Khách Hàng  : ");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 120, -1, -1));

        lb_NameCustomer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_NameCustomer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_NameCustomer.setText("null");
        jPanel2.add(lb_NameCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 120, 130, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Ngày             :");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 150, -1, -1));

        lb_DateOrder.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_DateOrder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_DateOrder.setText("null");
        jPanel2.add(lb_DateOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 150, 130, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Tổng Cộng    :");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 180, -1, -1));

        lb_TotalMoney.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_TotalMoney.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_TotalMoney.setText("null");
        jPanel2.add(lb_TotalMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 180, 100, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("VNĐ");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 180, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Khuyến Mãi   :");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 210, -1, -1));

        lb_Promotion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_Promotion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_Promotion.setText("null");
        jPanel2.add(lb_Promotion, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 210, 100, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("VNĐ");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 210, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Thành Tiền     :");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 240, -1, -1));

        lb_PayMoney.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_PayMoney.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_PayMoney.setText("null");
        jPanel2.add(lb_PayMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 240, 80, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("VNĐ");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 240, -1, -1));

        jScrollPane2.setBorder(null);

        tb_Order.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tb_Order.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Conan", "2", "5000", "10000"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên Truyện", "Số Lượng ", "Giá", "Thành Tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_Order.setFocusable(false);
        tb_Order.setRowHeight(25);
        tb_Order.setSelectionBackground(new java.awt.Color(0, 153, 153));
        jScrollPane2.setViewportView(tb_Order);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 320, 330, 220));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("----------           Danh Sách Order             ----------");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 290, 330, -1));

        date_From.setBackground(new java.awt.Color(255, 255, 255));
        date_From.setDateFormatString("dd/MM/yyyy");
        date_From.setFocusCycleRoot(true);
        date_From.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        date_From.setPreferredSize(new java.awt.Dimension(95, 25));
        jPanel2.add(date_From, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 170, 30));

        jLabel3.setText("To");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, -1, -1));

        date_To.setBackground(new java.awt.Color(255, 255, 255));
        date_To.setDateFormatString("dd/MM/yyyy");
        date_To.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(date_To, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 160, 30));

        btn_Fillter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Fillter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_filled_filter_26px.png"))); // NOI18N
        btn_Fillter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Fillter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_FillterMouseClicked(evt);
            }
        });
        jPanel2.add(btn_Fillter, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 40, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ExitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ExitMouseMoved
        btn_Exit.setBackground(new Color(204,0,0));
        btn_Exit.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btn_ExitMouseMoved

    private void btn_ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ExitMouseExited
        btn_Exit.setBackground(new Color(0,153,153));
        btn_Exit.setForeground(new Color(204,0,0));
    }//GEN-LAST:event_btn_ExitMouseExited

    private void btn_ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ExitMouseClicked
        FrmMain frm = new FrmMain();
        frm.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_ExitMouseClicked
    // khi cick sẽ lấy ra thông tin chi tiết của hóa đơn được click
    private void tb_BillMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_BillMouseReleased
        dongchon = tb_Bill.getSelectedRow();
        if(dongchon != -1)
        {
          
            try {
                lb_CodeBill.setText(listBill.get(dongchon).getId()+"");
                lb_NameCustomer.setText(listBill.get(dongchon).getName_customer());
                lb_NameEmployee.setText(listBill.get(dongchon).getName_employee());
                lb_DateOrder.setText(listBill.get(dongchon).getDate_order());
                lb_TotalMoney.setText(numf.format(listBill.get(dongchon).getTota_money())+"");
                lb_Promotion.setText(numf.format(listBill.get(dongchon).getPromotion())+"");
                lb_PayMoney.setText(numf.format(listBill.get(dongchon).getTota_money() - listBill.get(dongchon).getPromotion()) +"");
                LoadListOrderById(listBill.get(dongchon).getId());
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(FrmBill.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tb_BillMouseReleased

    private void txt_SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_SearchMouseClicked
        txt_Search.setText("");
    }//GEN-LAST:event_txt_SearchMouseClicked
    
    // tìm kiếm = mã hóa đơn
    private void txt_SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_SearchKeyReleased
        int id;
        try {
            id = Integer.parseInt(txt_Search.getText());
        } catch(Exception e) {
            return;
        }
        try {
            listBill = billModel.SearchById(id);
            LoadTableBill();
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(FrmBill.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txt_SearchKeyReleased
    // lọc hóa đơn theo thời gian
    private void btn_FillterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_FillterMouseClicked
        try {
            String from  = ((JTextField)date_From.getDateEditor().getUiComponent()).getText();
            String to  = ((JTextField)date_To.getDateEditor().getUiComponent()).getText();
            if(from.equals("") || to.equals(""))
            {
                return;
            }
            listBill = billModel.FillterBillByTime(from, to);
            LoadTableBill();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(FrmBill.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_FillterMouseClicked
    // xóa một hóa đơn
    private void btn_DeleteBillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DeleteBillMouseClicked
        
        if(dongchon != -1)
        {
            int close;
            close = JOptionPane.showConfirmDialog(null,"Xác nhận xóa","Thông báo",JOptionPane.YES_OPTION,JOptionPane.NO_OPTION);
            if(close == JOptionPane.NO_OPTION)
            {
                return;
            }
            try {
                int id = listBill.get(dongchon).getId();
                if(billModel.DeleteBill(id))
                {
                    listBill.remove(dongchon);
                    LoadTableBill();
                    JOptionPane.showMessageDialog(null,"Xóa thành công");
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Xóa thất bại");
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(FrmBill.class.getName()).log(Level.SEVERE, null, ex);
            }
            dongchon = -1;
        }
    }//GEN-LAST:event_btn_DeleteBillMouseClicked

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new FrmBill().setVisible(true);
                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(FrmBill.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_DeleteBill;
    private javax.swing.JLabel btn_Exit;
    private javax.swing.JLabel btn_Fillter;
    private com.toedter.calendar.JDateChooser date_From;
    private com.toedter.calendar.JDateChooser date_To;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lb_CodeBill;
    private javax.swing.JLabel lb_DateOrder;
    private javax.swing.JLabel lb_NameCustomer;
    private javax.swing.JLabel lb_NameEmployee;
    private javax.swing.JLabel lb_PayMoney;
    private javax.swing.JLabel lb_Promotion;
    private javax.swing.JLabel lb_TotalMoney;
    private javax.swing.JTable tb_Bill;
    private javax.swing.JTable tb_Order;
    private javax.swing.JTextField txt_Search;
    // End of variables declaration//GEN-END:variables
}
