/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import entity.Bill;
import entity.Commic;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import model.StatisticalModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import tablemodel.TableModelTopCommicSale;

/**
 *
 * @author Admin
 */
public class FrmStatistical extends javax.swing.JFrame {
    StatisticalModel sm = new StatisticalModel();
    ArrayList<Commic> listTopCommic = new ArrayList<>();
    ArrayList<Bill> listBill = new ArrayList<>();
    NumberFormat numf = NumberFormat.getInstance(); // định dạng số
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy"); // định dạng ngày tháng
    
    /**
     * Creates new form FrmStatistical
     */
    
    public void LoadTopCommic()
    {
        tb_AllTopCommic.setModel(new TableModelTopCommicSale(listTopCommic));
        tb_AllTopCommic.getColumnModel().getColumn(0).setPreferredWidth((int) (tb_AllTopCommic.getWidth()*0.2));
        tb_AllTopCommic.getColumnModel().getColumn(1).setPreferredWidth((int) (tb_AllTopCommic.getWidth()*0.5));
        tb_AllTopCommic.getColumnModel().getColumn(2).setPreferredWidth((int) (tb_AllTopCommic.getWidth()*0.5));
    }
    public void LoadListTopCommic() throws ClassNotFoundException, SQLException
    {
        listTopCommic = sm.getListTopCommic();
        LoadTopCommic();
    }    
    
    public void Chart() throws SQLException, ClassNotFoundException
    {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset = sm.Dataset();
         
        JFreeChart barChart = ChartFactory.createBarChart(
                "Doanh Thu Năm 2019",
                " ", "Doanh Thu",
                dataset, PlotOrientation.VERTICAL, false, true, false);
        
        
        CategoryPlot plot = barChart.getCategoryPlot();
        plot.setRangeGridlinePaint(Color.BLUE);
        plot.setBackgroundPaint(Color.WHITE);
        plot.setOutlinePaint(null);
       
        
        ChartPanel chartPanel = new ChartPanel(barChart);
        chartPanel.setPreferredSize(new Dimension(pn_Chart.getWidth(),pn_Chart.getHeight()));
        chartPanel.setOpaque(false);
        chartPanel.setBackground(new Color(255,255,255));
       
        
        pn_Chart.removeAll();
        pn_Chart.setLayout(new CardLayout());
        pn_Chart.add(chartPanel);
        pn_Chart.validate();
        pn_Chart.repaint();      
    }
    
    public FrmStatistical() throws ClassNotFoundException, SQLException {
        initComponents();
        setLocationRelativeTo(null);
        LoadListTopCommic();
        
        Chart();
        
        lb_AllMoney.setText(numf.format(sm.getTotalMoney())+ " VNĐ");
        lb_AllBill.setText(sm.getNumberBill()+"");
        lb_AllCommicSale.setText(sm.getNumberCommic()+"");
        
        tb_AllTopCommic.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,16));
        tb_AllTopCommic.getTableHeader().setOpaque(false);
        tb_AllTopCommic.getTableHeader().setBackground(new Color(0,0,0,0));
        tb_AllTopCommic.getTableHeader().setForeground(new Color(0,153,153));
        tb_AllTopCommic.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,16));
        
        Border border = BorderFactory.createLineBorder(new Color(0,153,153));
        tb_AllTopCommic.getTableHeader().setBorder(border);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_Exit = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_AllTopCommic = new javax.swing.JTable();
        pn_Chart = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lb_AllMoney = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lb_AllBill = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lb_AllCommicSale = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1119, 782));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_bullish_filled_100px.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Thống Kê");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));

        btn_Exit.setBackground(new java.awt.Color(0, 153, 153));
        btn_Exit.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn_Exit.setForeground(new java.awt.Color(204, 0, 0));
        btn_Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Exit.setText("x");
        btn_Exit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Exit.setOpaque(true);
        btn_Exit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_ExitMouseMoved(evt);
            }
        });
        btn_Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ExitMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_ExitMouseReleased(evt);
            }
        });
        jPanel2.add(btn_Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 0, 50, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 223));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);

        tb_AllTopCommic.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tb_AllTopCommic.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Top", "Tên Truyện", "Số Lượng Đã Bán"
            }
        ));
        tb_AllTopCommic.setFocusable(false);
        tb_AllTopCommic.setOpaque(false);
        tb_AllTopCommic.setRequestFocusEnabled(false);
        tb_AllTopCommic.setRowHeight(35);
        jScrollPane1.setViewportView(tb_AllTopCommic);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(742, 20, 380, 540));

        pn_Chart.setBackground(new java.awt.Color(204, 255, 204));
        pn_Chart.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(pn_Chart, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 740, 350));

        jPanel4.setBackground(new java.awt.Color(255, 102, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_cheap_2_filled_50px.png"))); // NOI18N
        jLabel3.setToolTipText("");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 50, 40));

        lb_AllMoney.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lb_AllMoney.setForeground(new java.awt.Color(255, 255, 255));
        lb_AllMoney.setText("1,000,000 VNĐ");
        jPanel4.add(lb_AllMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 30, 130, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 10, 60));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 200, 80));

        jPanel5.setBackground(new java.awt.Color(102, 102, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_bill_50px.png"))); // NOI18N
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 50, 40));

        lb_AllBill.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lb_AllBill.setForeground(new java.awt.Color(255, 255, 255));
        lb_AllBill.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_AllBill.setText("300");
        jPanel5.add(lb_AllBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 70, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel5.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 10, 60));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 190, 80));

        jPanel6.setBackground(new java.awt.Color(44, 175, 94));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_book_stack_52px.png"))); // NOI18N
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 60));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel6.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 10, 60));

        lb_AllCommicSale.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lb_AllCommicSale.setForeground(new java.awt.Color(255, 255, 255));
        lb_AllCommicSale.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_AllCommicSale.setText("500");
        jPanel6.add(lb_AllCommicSale, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 90, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 190, 80));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 740, 10));

        jDateChooser1.setDateFormatString("dd/MM/yyyy");
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 220, -1));

        jDateChooser2.setDateFormatString("dd/MM/yyyy");
        jDateChooser2.setFocusable(false);
        jPanel1.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 220, -1));

        jButton1.setText("Thống Kê");
        jButton1.setBorder(null);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 110, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_refresh_15px.png"))); // NOI18N
        jButton2.setBorder(null);
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 100, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 1120, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ExitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ExitMouseMoved
        btn_Exit.setBackground(new Color(204,0,0));
        btn_Exit.setForeground(new Color(255,255,255));
        
    }//GEN-LAST:event_btn_ExitMouseMoved

    private void btn_ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ExitMouseExited
        btn_Exit.setBackground(new Color(0,153,153));
        btn_Exit.setForeground(new Color(204,0,0));
    }//GEN-LAST:event_btn_ExitMouseExited
    // thoát
    private void btn_ExitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ExitMouseReleased
        FrmMain frm = new FrmMain();
        frm.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_ExitMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmStatistical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmStatistical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmStatistical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmStatistical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new FrmStatistical().setVisible(true);
                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(FrmStatistical.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_Exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lb_AllBill;
    private javax.swing.JLabel lb_AllCommicSale;
    private javax.swing.JLabel lb_AllMoney;
    private javax.swing.JPanel pn_Chart;
    private javax.swing.JTable tb_AllTopCommic;
    // End of variables declaration//GEN-END:variables
}
